### PR TITLE
Fix Breaking changes

### PR DESCRIPTION
**Pull request by SAtacker**
- The user is required to pass port within the URL string itself and
no separate parameter is accepted.

- Change the function calls and environment variable values

Signed-off-by: Shreyas Atre <shreyasatre16@gmail.com>

### CODE REVIEW

**Comment by juntao** [comment]
flows summarize

**Comment by juntao** [comment]
Hello, I am a [serverless review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/). Here are my reviews of code commits in this PR.

------

The first patch updates URL links in Cargo.toml files which should not pose any problems. The second patch changes a Rust function name to avoid overloading issues, while the third patch appears to update URL temporarily for testing purposes without introducing any issues but may cause some dependencies issues.

## Details

### Commit 1
The patch updates the URLs of the libraries in Cargo.toml files for repositories "dapr-sdk-wasi" to ensure they point to the main branch and original repository link. The changes are minor and do not appear to introduce any potential problems.

### Commit 2
The patch changes the implementation of the Rust code by renaming one of the functions to avoid problems with overloading/having functions with the same name but different number of arguments. Specifically, the function `new()` has its implementation moved to `new_with_url()` which receives a `String` parameter, and `new()` now calls `new_with_url()` with a hardcoded value in `url_base`. The changes seem to be correct and should not pose compatibility issues.

### Commit 3
This patch updates the URL for `dapr_sdk_wasi` in the `Cargo.toml` file from the Second State organization's repository to the user's own forked repository. The change seems to be temporary and made for some testing purposes or experimentation. 

There do not seem to be any potential problems or errors resulting from this patch, as it only updates the URL and does not make any major changes to the codebase. However, it's possible that this change could cause dependency issues if the user's forked repository is not in sync with the original repository or if the user has diverged significantly from the main codebase. Furthermore, the change raises the question of whether the permanent change to be merged would also include such temporary changes.

**Comment by juntao** [comment]
I guess the `new_with_url()` function should just take a single argument? There does not seem to be a need to separate the port and base in this case. Perhaps `new_with_url("http://localhost:3501")` would suffice? Thanks.

**Comment by juntao** [comment]
flows summarize

**Comment by juntao** [comment]
Hello, I am a [serverless review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/). Here are my reviews of code commits in this PR.

------

Overall Summary:

In the provided summaries, the source code patches include updates to the 'dapr_sdk_wasi' dependency URL and branch, the addition of a new function `new_with_url`, and modifications to the existing `new` function in the `impl Dapr` struct. The changes were made in 'examples/echo/Cargo.toml', 'examples/tests/Cargo.toml', and 'examples/tests/src/main.rs' files.

Potential Issues and Errors:

1. The new URL or the branch for the 'dapr_sdk_wasi' dependency might not have the required functionality, leading to compatibility issues if there are differences between the 'docker_compose' and 'main' branches.
2. Other parts of the project or dependencies relying on the 'docker_compose' branch of 'dapr_sdk_wasi' might be affected by the change, causing unexpected behavior or performance issues.
3. The change in the 'dapr_sdk_wasi' URL points to a personal repository, which could lead to discrepancies in the codebases or security vulnerabilities. It is important to ensure the personal repository contains the necessary code changes and is safe to use.
4. The addition of the `new_with_url` function and modifications to the existing `new` function might lead to confusion, duplicated code, or maintenance issues in the future, indicating that more efficient alternatives like the builder pattern might be considered.

Most Important Findings:

1. The dependency URL and branch for 'dapr_sdk_wasi' have been updated in both 'examples/echo/Cargo.toml' and 'examples/tests/Cargo.toml' files.
2. A new function `new_with_url` has been created in `impl Dapr`, and the existing `new` function has been modified.
3. The 'examples/tests/src/main.rs' file has been updated to use the `new_with_url` function instead of the `new` function.

## Details

### Commit 1
Summary of Key Changes:
1. The URL for 'dapr_sdk_wasi' dependency is updated in both 'examples/echo/Cargo.toml' and 'examples/tests/Cargo.toml' files.
2. The branch for the 'dapr_sdk_wasi' dependency is changed from 'docker_compose' to 'main' in both files.

Potential Problems:
1. The new URL or the branch might not have the required functionality if there are differences between the 'docker_compose' and 'main' branches.
2. There could be compatibility issues if other parts of the project rely on the 'docker_compose' branch of 'dapr_sdk_wasi' dependency.
3. If any other dependencies rely on the 'docker_compose' branch, they might be affected by the change leading to unexpected behavior or performance issues.

### Commit 2
Summary of key changes:
1. Created a new function `new_with_url` in `impl Dapr` which takes `port` and `url_base_` as arguments and initializes a `Dapr` struct.
2. The previous function `new` has been modified to only take `port` as an argument and internally calls the new `new_with_url` function with "http://localhost:" as the default URL.
3. The `main` in `examples/tests/src/main.rs` has been updated to use `new_with_url` instead of `new`, passing the required URL.

Potential problems:
1. The new function `new_with_url` has likely been created to fix a breaking change due to Rust's restrictions on overloading functions. However, this workaround might lead to confusion or duplicated code if more functions with similar names are added later. A better approach could involve using different structs for different configurations to maintain a clear distinction.
2. The solution now has two separate functions (`new` and `new_with_url`) for constructing a `Dapr` instance in different ways. This might be a potential source of inconsistency and might require extra maintenance in the future as the library evolves. A more structured approach, like using the builder pattern, might be more efficient in the long run.

### Commit 3
Summary of key changes:
- The dependency `dapr_sdk_wasi` URL has been changed in the Cargo.toml file.

Potential problems:
1. The change in URL points to a personal repository (github.com/SAtacker) rather than the official repository (github.com/second-state). This could be an oversight or a temporary change, but it could lead to discrepancies in the codebases or security vulnerabilities.
2. Make sure that the personal repository contains the necessary code changes and is safe to use in this project. It may be better to merge changes into the official repository and reference that instead.

**Comment by SAtacker** [comment]
> I guess the `new_with_url()` function should just take a single argument? There does not seem to be a need to separate the port and base in this case. Perhaps `new_with_url("http://localhost:3501")` would suffice? Thanks.

Oh, so we should just take a string and use regex/string manipulations to parse for a port number?

**Comment by juntao** [comment]
> > I guess the `new_with_url()` function should just take a single argument? There does not seem to be a need to separate the port and base in this case. Perhaps `new_with_url("http://localhost:3501")` would suffice? Thanks.
> 
> Oh, so we should just take a string and use regex/string manipulations to parse for a port number?

Do we really need to know the port number as a separate entity? Or, do we just need the complete base URL that contains the port number?

**Comment by SAtacker** [comment]
> > > I guess the `new_with_url()` function should just take a single argument? There does not seem to be a need to separate the port and base in this case. Perhaps `new_with_url("http://localhost:3501")` would suffice? Thanks.
> > 
> > Oh, so we should just take a string and use regex/string manipulations to parse for a port number?
> 
> Do we really need to know the port number as a separate entity? Or, do we just need the complete base URL that contains the port number?

I agree, that'll work, probably overthought this.

**Comment by juntao** [comment]
flows summarize again

**Comment by juntao** [comment]
Hello, I am a [serverless review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/). Here are my reviews of code commits in this PR.

------

In summary, these patches involve updates to the `dapr_sdk_wasi` dependency repository links and the introduction of new functions and changes to existing ones in the `Dapr` struct. There are several potential issues and errors that might arise due to these changes:

1. The first patch updates the dependency repository links and branches, introducing a potential problem with using a forked repository instead of the original one. This could lead to unintended consequences and requires a careful review of the forked repository.

2. The second patch introduces the `new_with_url` function and modifies the existing `new` function. This might break existing code that relies on the old function signatures. Moreover, the hard-coded default URL and the changes in function signatures might affect flexibility and convenience for users.

3. The third patch changes the URL of the dapr_sdk_wasi dependency again, pointing back to a forked repository. Similar concerns mentioned in the first patch arise, such as being out of sync with the original repository or possible malicious code in the forked version.

4. The fourth patch further modifies the `new` function and updates other parts of the code base accordingly. It introduces potential issues related to breaking user code, hardcoded port numbers in URLs, and the removal of the separate `new` function, which might affect users who only want to specify a port number.

Suggested actions include investigating the forked repository usage, reviewing the impact of changes on existing users, ensuring proper documentation for updated functions, and considering flexibility and convenience for users during the transition.

## Details

### Commit 1
The patch does the following:

1. Changes the source repository link for `dapr_sdk_wasi` dependency in two Cargo.toml files (examples/echo/Cargo.toml and examples/tests/Cargo.toml) from `https://github.com/SAtacker/dapr-sdk-wasi` to `https://github.com/second-state/dapr-sdk-wasi`.
2. Changes the branch tracked in both files for `dapr_sdk_wasi` from "docker_compose" to "main".

Key findings and potential problems:

1. The patch successfully updates the URL to point to the original repository instead of a fork.
2. The change in the branch also tracks the main branch instead of the specific "docker_compose" branch.

There doesn't seem to be any potential problems with this patch.

### Commit 2
Summary of key changes:

1. A new function `new_with_url` has been added to the `Dapr` struct in `src/lib.rs`, which takes both `port` and `url_base_` as arguments.
2. The original `new` function in the `Dapr` struct has been updated to call the new `new_with_url` function, passing only the `port` argument and a default base URL of "http://localhost".
3. In `examples/tests/src/main.rs`, the invocation of `new` function is updated to use the new `new_with_url` function as it requires providing a URL.

Potential problems:

1. The addition of the new function `new_with_url` might break the existing code that uses the old `new` function expecting to pass a custom URL as a second argument. This might be mitigated by providing clear documentation of the changes and an update in the usage examples.
2. The default URL in the new `new` function is hard-coded as "http://localhost", which limits the function's flexibility. It would be better to create a constant for this default value or make it configurable via environment variables or a configuration file.

### Commit 3
Summary of changes:
- The patch makes changes to the URL of the dapr_sdk_wasi dependency in `examples/tests/Cargo.toml`
- The original URL is `https://github.com/second-state/dapr-sdk-wasi`
- The new URL is `https://github.com/SAtacker/dapr-sdk-wasi`

Potential problems:
1. The new URL points to a forked repository. It might not be up to date with the original repository or might contain additional changes that are not part of the official version.
2. The patch is changing the source of dependency, which could have unintended consequences for the project. Review the fork to ensure it is a trustworthy source and does not contain malicious code or vulnerabilities.

Recommendations:
- Investigate the purpose behind using the forked repository instead of the original one.
- If required, consider requesting the author to create a pull request to the original repository with any necessary changes and keep using the original repo as a dependency source.

### Commit 4
This patch mainly modifies the `new` function for the `Dapr` struct in the `src/lib.rs` file. It also updates the usage of this function in `examples/tests/src/main.rs` and the environment variable in `examples/docker_compose/docker-compose.yaml`. Here are the key changes:

1. The `new` function now accepts only a single string parameter containing the URL, including the port number. Previously, it accepted a separate port parameter.
2. The `new_with_url` function has been updated and renamed to `new`.
3. The `EXAMPLE_DAPR_URL` environment variable in the `docker-compose.yaml` file has been updated to include the port number.
4. The calls to the `new` function in `main.rs` have been updated to match the new function signature.

Potential problems:

1. The biggest concern is the potential breakage of existing user code, since anyone using the `new_with_url` function, now replaced by `new`, would have to update their code to match the new function signature.
2. Hardcoding the port number in the URLs in the `docker-compose.yaml` and `main.rs` files may make them less flexible if the port number needs to be changed later.
3. The removal of the separate `new` function that previously used a default URL could create inconvenience for users who only want to specify the port number.

It is recommended to consider the impact of these changes on existing users and ensure proper documentation to avoid confusion during the transition.

**Comment by juntao** [comment]
Hmm, I do not think this is right ... The purpose of this PR is to maintain compatibility with older versions of the SDK. The `new()` function signature in older versions is 

```
new(port: u32)
```

It is now changed to 

```
new(url: String)
```

which is still incompatible. I think we need

```
new(port: u32)
new_with_url(url: String)
```

**Pull request merged**
